server:
  port: 8008

spring:
  application:
    name: matchsys-provider-8008
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.80.128:3306/matchsys?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root




mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

eureka:
  instance:
    instance-id: ${spring.application.name}-${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7007/eureka/
info:
  remark: 这是一个提供者，提供各个表的增删改查
  author: lalala

